/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
[ERROR 2020-11-22 16:08:49,129] function_runner.py: 254  Runner Thread raised error.
Traceback (most recent call last):
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "run.py", line 7, in trainable
    train.Experiment(**config['experiment_config']).train(**config['train_config'])
  File "/home/avandekl/Documents/thesis/train.py", line 186, in train
    next_obs_dict, reward, done, info = self.env.step(action)
  File "/home/avandekl/Documents/thesis/wrappers.py", line 68, in step
    reward = self.compute_reward(
  File "/home/avandekl/Documents/thesis/wrappers.py", line 85, in compute_reward
    latent_achieved_goal = self._to_latent(achieved_goal)
  File "/home/avandekl/Documents/thesis/wrappers.py", line 78, in _to_latent
    latent = self.encoder.forward_single_observation(observation)
  File "/home/avandekl/Documents/thesis/agent.py", line 57, in forward_single_observation
    observation = self.conv(observation)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: expected scalar type Double but found Float
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/avandekl/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 267, in run
    raise e
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "run.py", line 7, in trainable
    train.Experiment(**config['experiment_config']).train(**config['train_config'])
  File "/home/avandekl/Documents/thesis/train.py", line 186, in train
    next_obs_dict, reward, done, info = self.env.step(action)
  File "/home/avandekl/Documents/thesis/wrappers.py", line 68, in step
    reward = self.compute_reward(
  File "/home/avandekl/Documents/thesis/wrappers.py", line 85, in compute_reward
    latent_achieved_goal = self._to_latent(achieved_goal)
  File "/home/avandekl/Documents/thesis/wrappers.py", line 78, in _to_latent
    latent = self.encoder.forward_single_observation(observation)
  File "/home/avandekl/Documents/thesis/agent.py", line 57, in forward_single_observation
    observation = self.conv(observation)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/avandekl/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: expected scalar type Double but found Float
